name: message-sa

channels:
    - conda-forge

dependencies:
    - python=3.7
    - numpy=1.17.1
    - pandas=0.25.1
    - matplotlib=3.1.1
    - jupyterlab=1.1.4
    - seaborn=0.9.0
    - ipykernel=5.1.3
    - message-ix=1.2.0
